### ISSUE TITLE
MacOs No active package get_cli.

### ISSUE THREAD

**Issue by burqman01** [jonataslaw/get_cli#149]
```
berkay@iMac-von-Berkay doner_production % get init
Can't load Kernel binary: Invalid kernel binary format version.
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ The Dart tool uses Google Analytics to report feature usage statistics     ║
  ║ and to send basic crash reports. This data is used to help improve the     ║
  ║ Dart platform and tools over time.                                         ║
  ║                                                                            ║
  ║ To disable reporting of analytics, run:                                    ║
  ║                                                                            ║
  ║   dart --disable-analytics                                                 ║
  ║                                                                            ║
  ╚════════════════════════════════════════════════════════════════════════════╝

No active package get_cli.
berkay@iMac-von-Berkay doner_production % flutter pub global activate get_cli
Package get_cli is currently active at version 1.6.0.
Resolving dependencies...
+ _fe_analyzer_shared 32.0.0
+ analyzer 3.0.0
+ ansicolor 2.0.1
+ args 2.3.0
+ async 2.8.2
+ charcode 1.3.1
+ cli_dialog 0.5.0
+ cli_util 0.3.5
+ clock 1.1.0
+ collection 1.15.0
+ convert 3.0.1
+ crypto 3.0.1
+ dart_console 1.0.0
+ dart_style 2.2.1
+ ffi 1.1.2
+ file 6.1.2
+ get_cli 1.7.1
+ glob 2.0.2
+ http 0.13.4
+ http_parser 4.0.0
+ intl 0.17.0
+ matcher 0.12.11
+ meta 1.7.0
+ package_config 2.0.2
+ path 1.8.0
+ process_run 0.12.2+2
+ pub_semver 2.1.0
+ pubspec 2.0.1
+ quiver 3.0.1+1
+ recase 4.0.0
+ source_span 1.8.1
+ stack_trace 1.10.0
+ string_scanner 1.1.0
+ synchronized 3.0.0
+ term_glyph 1.2.0
+ typed_data 1.3.0
+ uri 1.0.0
+ version 2.0.0
+ watcher 1.0.1
+ win32 2.3.1
+ yaml 3.1.0
Downloading get_cli 1.7.1...
Downloading dart_style 2.2.1...
Downloading analyzer 3.0.0...
Downloading _fe_analyzer_shared 32.0.0...
Installed executables get and getx.
Warning: Executable "get" runs "bin/get.dart", which was not found in get_cli.
Warning: Executable "getx" runs "bin/get.dart", which was not found in get_cli.
Activated get_cli 1.7.1.
berkay@iMac-von-Berkay doner_production % flutter upgrade
Upgrading Flutter to 2.8.1 from 2.8.0 in /Users/berkay/Documents/Dev/flutter...
Downloading Dart SDK from Flutter engine 890a5fca2e34db413be624fc83aeea8e61d42ce6...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  205M    0  197k    0     0   491k      0  0:07:07 --:--:--  0:07:07  499k
  4  205M    4 9182k    0     0  6547k      0  0:00:32  0:00:01  0:00:31 6577k
  8  205M    8 17.8M    0     0  7614k      0  0:00:27  0:00:02  0:00:25 7632k
 13  205M   13 26.9M    0     0  8122k      0  0:00:25  0:00:03  0:00:22 8136k
 17  205M   17 36.1M    0     0  8403k      0  0:00:25  0:00:04  0:00:21 8414k
 21  205M   21 44.0M    0     0  8351k      0  0:00:25  0:00:05  0:00:20 8984k
 25  205M   25 53.1M    0     0  8495k      0  0:00:24  0:00:06  0:00:18 9041k
 30  205M   30 62.2M    0     0  8614k      0  0:00:24  0:00:07  0:00:17 9094k
 34  205M   34 71.2M    0     0  8683k      0  0:00:24  0:00:08  0:00:16 9065k
 38  205M   38 80.1M    0     0  8724k      0  0:00:24  0:00:09  0:00:15 9007k
 43  205M   43 89.2M    0     0  8785k      0  0:00:23  0:00:10  0:00:13 9254k
 47  205M   47 97.1M    0     0  8721k      0  0:00:24  0:00:11  0:00:13 9011k
 51  205M   51  106M    0     0  8773k      0  0:00:23  0:00:12  0:00:11 9011k
 55  205M   55  114M    0     0  8770k      0  0:00:23  0:00:13  0:00:10 8915k
 60  205M   60  124M    0     0  8828k      0  0:00:23  0:00:14  0:00:09 9024k
 64  205M   64  133M    0     0  8861k      0  0:00:23  0:00:15  0:00:08 9019k
 68  205M   68  140M    0     0  8798k      0  0:00:23  0:00:16  0:00:07 8976k
 72  205M   72  149M    0     0  8815k      0  0:00:23  0:00:17  0:00:06 8918k
 77  205M   77  158M    0     0  8845k      0  0:00:23  0:00:18  0:00:05 9046k
 81  205M   81  168M    0     0  8872k      0  0:00:23  0:00:19  0:00:04 8998k
 86  205M   86  177M    0     0  8897k      0  0:00:23  0:00:20  0:00:03 9009k
 90  205M   90  184M    0     0  8850k      0  0:00:23  0:00:21  0:00:02 9020k
 94  205M   94  193M    0     0  8856k      0  0:00:23  0:00:22  0:00:01 8997k
 98  205M   98  202M    0     0  8882k      0  0:00:23  0:00:23 --:--:-- 9020k
100  205M  100  205M    0     0  8887k      0  0:00:23  0:00:23 --:--:-- 8960k
Building flutter tool...

Upgrading engine...
Downloading android-arm-profile/darwin-x64 tools...                614ms
Downloading android-arm-release/darwin-x64 tools...                267ms
Downloading android-arm64-profile/darwin-x64 tools...              605ms
Downloading android-arm64-release/darwin-x64 tools...              492ms
Downloading android-x64-profile/darwin-x64 tools...                514ms
Downloading android-x64-release/darwin-x64 tools...                507ms
Downloading android-x86 tools...                                 2.785ms
Downloading android-x64 tools...                                 2.619ms
Downloading android-arm tools...                                   967ms
Downloading android-arm-profile tools...                           719ms
Downloading android-arm-release tools...                           491ms
Downloading android-arm64 tools...                               1.377ms
Downloading android-arm64-profile tools...                         786ms
Downloading android-arm64-release tools...                         528ms
Downloading android-x64-profile tools...                           953ms
Downloading android-x64-release tools...                           436ms
Downloading android-x86-jit-release tools...                     1.003ms
Downloading ios tools...                                            6,4s
Downloading ios-profile tools...                                 2.145ms
Downloading ios-release tools...                                    6,8s
Downloading Web SDK...                                           1.193ms
Downloading CanvasKit...                                           744ms
Downloading package sky_engine...                                  188ms
Downloading flutter_patched_sdk tools...                           440ms
Downloading flutter_patched_sdk_product tools...                   429ms
Downloading darwin-x64 tools...                                     3,8s
Downloading darwin-x64/font-subset tools...                        156ms

Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (7 hours ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.61.2)
[✓] Connected device (1 available)

• No issues found!
berkay@iMac-von-Berkay doner_production % get init
No active package get_cli.
berkay@iMac-von-Berkay doner_production % pub global activate get_cli 
zsh: command not found: pub
berkay@iMac-von-Berkay doner_production % get
No active package get_cli.
berkay@iMac-von-Berkay doner_production % flutter pub global deactivate get_cli
Deactivated package get_cli 1.7.1.
berkay@iMac-von-Berkay doner_production % flutter pub global activate get_cli
Resolving dependencies...
+ _fe_analyzer_shared 32.0.0
+ analyzer 3.0.0
+ ansicolor 2.0.1
+ args 2.3.0
+ async 2.8.2
+ charcode 1.3.1
+ cli_dialog 0.5.0
+ cli_util 0.3.5
+ clock 1.1.0
+ collection 1.15.0
+ convert 3.0.1
+ crypto 3.0.1
+ dart_console 1.0.0
+ dart_style 2.2.1
+ ffi 1.1.2
+ file 6.1.2
+ get_cli 1.7.1
+ glob 2.0.2
+ http 0.13.4
+ http_parser 4.0.0
+ intl 0.17.0
+ matcher 0.12.11
+ meta 1.7.0
+ package_config 2.0.2
+ path 1.8.1
+ process_run 0.12.3+1
+ pub_semver 2.1.0
+ pubspec 2.0.1
+ quiver 3.0.1+1
+ recase 4.0.0
+ source_span 1.8.1
+ stack_trace 1.10.0
+ string_scanner 1.1.0
+ synchronized 3.0.0
+ term_glyph 1.2.0
+ typed_data 1.3.0
+ uri 1.0.0
+ version 2.0.0
+ watcher 1.0.1
+ win32 2.3.1
+ yaml 3.1.0
Downloading path 1.8.1...
Downloading process_run 0.12.3+1...
Installed executables get and getx.
Warning: Executable "get" runs "bin/get.dart", which was not found in get_cli.
Warning: Executable "getx" runs "bin/get.dart", which was not found in get_cli.
Activated get_cli 1.7.1.
berkay@iMac-von-Berkay doner_production % get init
No active package get_cli.
berkay@iMac-von-Berkay doner_production % get
No active package get_cli.
berkay@iMac-von-Berkay doner_production % pub global activate get_cli 1.3.11
zsh: command not found: pub
berkay@iMac-von-Berkay doner_production % flutter pub global activate get_cli 1.3.11
Package get_cli is currently active at version 1.7.1.
Resolving dependencies...
+ _fe_analyzer_shared 14.0.0 (32.0.0 available)
+ analyzer 0.41.2 (3.0.0 available)
+ ansicolor 1.1.1 (2.0.1 available)
+ archive 2.0.13 (3.1.6 available)
+ args 1.6.0 (2.3.0 available)
+ async 2.8.2
+ charcode 1.3.1
+ cli_dialog 0.3.3 (0.5.0 available)
+ cli_menu 0.2.3
+ cli_util 0.2.0 (0.3.5 available)
+ collection 1.15.0
+ convert 2.1.1 (3.0.1 available)
+ crypto 2.1.5 (3.0.1 available)
+ dart_style 1.3.12 (2.2.1 available)
+ file 6.1.2
+ get_cli 1.3.11 (1.7.1 available)
+ glob 2.0.2
+ grapheme_splitter 1.0.0
+ http 0.12.2 (0.13.4 available)
+ http_parser 3.1.4 (4.0.0 available)
+ intl 0.16.1 (0.17.0 available)
+ io 1.0.3
+ json_ast 1.0.5
+ meta 1.7.0
+ package_config 1.9.3 (2.0.2 available)
+ path 1.8.1
+ pedantic 1.11.1
+ process_run 0.10.12+3 (0.12.3+1 available)
+ pub_semver 2.1.0
+ recase 3.0.1 (4.0.0 available)
+ source_span 1.8.1
+ string_scanner 1.1.0
+ term_glyph 1.2.0
+ typed_data 1.3.0
+ version 1.3.1 (2.0.0 available)
+ watcher 1.0.1
+ yaml 2.2.1 (3.1.0 available)
Downloading get_cli 1.3.11...
Downloading yaml 2.2.1...
Downloading json_ast 1.0.5...
Downloading intl 0.16.1...
Downloading cli_dialog 0.3.3...
Downloading archive 2.0.13...
Downloading grapheme_splitter 1.0.0...
Downloading recase 3.0.1...
Downloading cli_menu 0.2.3...
Downloading cli_util 0.2.0...
Downloading version 1.3.1...
Downloading process_run 0.10.12+3...
Downloading ansicolor 1.1.1...
Downloading args 1.6.0...
Downloading crypto 2.1.5...
Downloading convert 2.1.1...
Downloading dart_style 1.3.12...
Downloading analyzer 0.41.2...
Downloading _fe_analyzer_shared 14.0.0...
Downloading package_config 1.9.3...
Installed executable get.
Warning: Executable "get" runs "bin/get.dart", which was not found in get_cli.
Activated get_cli 1.3.11.
berkay@iMac-von-Berkay doner_production % get init
No active package get_cli.
berkay@iMac-von-Berkay doner_production % pub global deactivate get_cli     
zsh: command not found: pub
berkay@iMac-von-Berkay doner_production % flutter pub global deactivate get_cli
Deactivated package get_cli 1.3.11.
berkay@iMac-von-Berkay doner_production % pub global activate get_cli 1.3.11   
zsh: command not found: pub
berkay@iMac-von-Berkay doner_production % flutter pub global activate get_cli 1.3.11
Resolving dependencies...
+ _fe_analyzer_shared 14.0.0 (32.0.0 available)
+ analyzer 0.41.2 (3.0.0 available)
+ ansicolor 1.1.1 (2.0.1 available)
+ archive 2.0.13 (3.1.6 available)
+ args 1.6.0 (2.3.0 available)
+ async 2.8.2
+ charcode 1.3.1
+ cli_dialog 0.3.3 (0.5.0 available)
+ cli_menu 0.2.3
+ cli_util 0.2.0 (0.3.5 available)
+ collection 1.15.0
+ convert 2.1.1 (3.0.1 available)
+ crypto 2.1.5 (3.0.1 available)
+ dart_style 1.3.12 (2.2.1 available)
+ file 6.1.2
+ get_cli 1.3.11 (1.7.1 available)
+ glob 2.0.2
+ grapheme_splitter 1.0.0
+ http 0.12.2 (0.13.4 available)
+ http_parser 3.1.4 (4.0.0 available)
+ intl 0.16.1 (0.17.0 available)
+ io 1.0.3
+ json_ast 1.0.5
+ meta 1.7.0
+ package_config 1.9.3 (2.0.2 available)
+ path 1.8.1
+ pedantic 1.11.1
+ process_run 0.10.12+3 (0.12.3+1 available)
+ pub_semver 2.1.0
+ recase 3.0.1 (4.0.0 available)
+ source_span 1.8.1
+ string_scanner 1.1.0
+ term_glyph 1.2.0
+ typed_data 1.3.0
+ version 1.3.1 (2.0.0 available)
+ watcher 1.0.1
+ yaml 2.2.1 (3.1.0 available)
Installed executable get.
Warning: Executable "get" runs "bin/get.dart", which was not found in get_cli.
Activated get_cli 1.3.11.
berkay@iMac-von-Berkay doner_production % get init
No active package get_cli.
berkay@iMac-von-Berkay doner_production % flutter get 
Could not find a command named "get".

Did you mean one of these?
  test



Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
berkay@iMac-von-Berkay doner_production % flutter getx
Could not find a command named "getx".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
berkay@iMac-von-Berkay doner_production % get
No active package get_cli.
berkay@iMac-von-Berkay doner_production % get update
No active package get_cli.
berkay@iMac-von-Berkay doner_production % get upgrade
No active package get_cli.
berkay@iMac-von-Berkay doner_production % 
```

**Comment by brasizza** [comment]
try this command 

dart pub global activate get_cli

**Comment by bongcoy** [comment]
I think there is a problem with your Environment Variables / System PATH

had you add your "[FlutterSDKInstallDir]\bin\cache\dart-sdk\bin" to your system path ?

**Comment by bongcoy** [comment]
> dart pub global activate get_cli

Okay it fixed the 

```
Warning: Executable "get" runs "bin/get.dart", which was not found in get_cli.
Warning: Executable "get" runs "bin/get.dart", which was not found in get_cli.
```

but when I try to run "get create project"
I got message like this : 
```
Unhandled exception:
Null check operator used on a null value
#0      ListChooser._userInput (package:cli_dialog/src/list_chooser.dart:126:27)
#1      ListChooser.choose (package:cli_dialog/src/list_chooser.dart:46:21)
#2      CLI_Dialog._getListAnswer (package:cli_dialog/src/dialog.dart:352:27)
#3      CLI_Dialog._askListQuestion (package:cli_dialog/src/dialog.dart:148:5)
#4      CLI_Dialog._standardOrderNoNavigation (package:cli_dialog/src/dialog.dart:473:7)
#5      CLI_Dialog._standardOrder (package:cli_dialog/src/dialog.dart:458:7)
#6      CLI_Dialog.ask (package:cli_dialog/src/dialog.dart:129:7)
#7      Menu.choose (package:get_cli/common/menu/menu.dart:17:27)
#8      CreateProjectCommand.execute (package:get_cli/commands/impl/create/project/project.dart:27:25)
#9      main (file:///C:/Users/myuname/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/get_cli-1.7.1/bin/get.dart:18:23)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```
Why did it happen
