### ISSUE TITLE
Invalid kernel binary format version. on get_cli 1.7.1

### ISSUE THREAD

**Issue by heshesh2010** [jonataslaw/get_cli#171]
Hi , 

when I update to version 1.7.1 and run : get update I got error 

```
Can't load Kernel binary: Invalid kernel binary format version.
Precompiling executable... (6.4s)
Failed to precompile get_cli:get:
Crash when compiling null,
at character offset null:
type 'InvalidType' is not a subtype of type 'InterfaceType' in type cast
#0      _FfiDefinitionTransformer._checkFieldAnnotations (package:vm/transformations/ffi_definitions.dart:288:31)
#1      _FfiDefinitionTransformer.visitClass (package:vm/transformations/ffi_definitions.dart:188:25)
#2      Class.accept (package:kernel/ast.dart:1347:38)
#3      transformList (package:kernel/ast.dart:11035:32)
#4      Library.transformChildren (package:kernel/ast.dart:628:5)
#5      Transformer.defaultTreeNode (package:kernel/visitor.dart:680:10)
#6      TreeVisitor.visitLibrary (package:kernel/visitor.dart:277:35)
#7      _FfiDefinitionTransformer.visitLibrary (package:vm/transformations/ffi_definitions.dart:164:18)
#8      List.forEach (dart:core-patch/growable_array.dart:403:8)
#9      transformLibraries (package:vm/transformations/ffi_definitions.dart:85:13)
#10     VmTarget.performModularTransformationsOnLibraries (package:vm/target/vm.dart:158:32)
#11     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1270:19)
#12     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:406:7)
<asynchronous suspension>
#13     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#14     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:164:19)
<asynchronous suspension>
#15     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#16     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:12)
<asynchronous suspension>
#17     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:10)
<asynchronous suspension>
#18     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:11)
<asynchronous suspension>
#19     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:396:11)
<asynchronous suspension>
#20     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:212:45)
<asynchronous suspension>
#21     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:872:37)
<asynchronous suspension>


#0      _FfiDefinitionTransformer._checkFieldAnnotations (package:vm/transformations/ffi_definitions.dart:288:31)
#1      _FfiDefinitionTransformer.visitClass (package:vm/transformations/ffi_definitions.dart:188:25)
#2      Class.accept (package:kernel/ast.dart:1347:38)
#3      transformList (package:kernel/ast.dart:11035:32)
#4      Library.transformChildren (package:kernel/ast.dart:628:5)
#5      Transformer.defaultTreeNode (package:kernel/visitor.dart:680:10)
#6      TreeVisitor.visitLibrary (package:kernel/visitor.dart:277:35)
#7      _FfiDefinitionTransformer.visitLibrary (package:vm/transformations/ffi_definitions.dart:164:18)
#8      List.forEach (dart:core-patch/growable_array.dart:403:8)
#9      transformLibraries (package:vm/transformations/ffi_definitions.dart:85:13)
#10     VmTarget.performModularTransformationsOnLibraries (package:vm/target/vm.dart:158:32)
#11     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1270:19)
#12     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:406:7)
<asynchronous suspension>
#13     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#14     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:164:19)
<asynchronous suspension>
#15     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#16     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:12)
<asynchronous suspension>
#17     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:10)
<asynchronous suspension>
#18     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:11)
<asynchronous suspension>
#19     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:396:11)
<asynchronous suspension>
#20     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:212:45)
<asynchronous suspension>
#21     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:872:37)
<asynchronous suspension>

```

so when I run  flutter pub global activate get_cli it returns me to 1.6.0

**Comment by heshesh2010** [comment]
i just run brew upgrade dart
 and it fixed
