### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by kulame** [jonataslaw/get_cli#237]
```bash
PS C:\code\getx\rem> get create page:set-act
Can't load Kernel binary: Invalid SDK hash.
✓  文件: set_act_controller.dart 创建成功，路径: lib\app\modules\set-act\\controllers\\set_act_controller.dart
✓  文件: set_act_view.dart 创建成功，路径: lib\app\modules\set-act\\views\\set_act_view.dart
✓  文件: set_act_binding.dart 创建成功，路径: lib\app\modules\set-act\\bindings\\set_act_binding.dart
✓  set-act route 创建成功.
✓  SetAct page 创建成功.
✖  + HandshakeException: Connection terminated during handshake

Unhandled exception:
Null check operator used on a null value
#0      checkForUpdate.<anonymous closure>.<anonymous closure> (package:get_cli/functions/version/version_update.dart:23:51)
<asynchronous suspension>
#1      checkForUpdate.<anonymous closure> (package:get_cli/functions/version/version_update.dart:19:9)
<asynchronous suspension>
#2      checkForUpdate (package:get_cli/functions/version/version_update.dart:17:7)
<asynchronous suspension>
#3      main (file:///C:/src/flutter/bin/cache/hosted/pub.flutter-io.cn/get_cli-1.8.4/bin/get.dart:18:9)
<asynchronous suspension>

PS C:\code\getx\rem> get --version
Can't load Kernel binary: Invalid SDK hash.

[--version] 是多余的

░██████╗░███████╗████████╗   ░█████╗░██╗░░░░░░██╗
██╔════╝░██╔════╝╚══██╔══╝   ██╔══██╗██║░░░░░░██║
██║░░██╗░█████╗░░░░░██║░░░   ██║░░╚═╝██║░░░░░░██║
██║░░╚██╗██╔══╝░░░░░██║░░░   ██║░░██╗██║░░░░░░██║
╚██████╔╝███████╗░░░██║░░░   ╚█████╔╝███████╗ ██║
░╚═════╝░╚══════╝░░░╚═╝░░░   ░╚════╝░╚══════╝ ╚═╝

Version: 1.8.4
```

Is there any problem here? 🤔

**Comment by xyhuangjia** [comment]
#181

**Comment by partha-zoozle** [comment]
@xyhuangjia  Got any solution for this ?

**Comment by xyhuangjia** [comment]
> [@xyhuangjia](https://github.com/xyhuangjia) Got any solution for this ?

run `flutter pub global activate get_cli`

**Comment by partha-zoozle** [comment]
@xyhuangjia  i tried but still getting issue 
Null check operator used on a null value
#0      PubspecUtils.nullSafeSupport (package:get_cli/common/utils/pubspec/pubspec_utils.dart:146:76)
#1      new TypeDefinition (package:get_cli/common/utils/json_serialize/sintaxe.dart:81:22)
#2      new TypeDefinition.fromDynamic (package:get_cli/common/utils/json_serialize/sintaxe.dart:68:12)
#3      ModelGenerator._generateClassDefinition (package:get_cli/common/utils/json_serialize/model_generator.dart:68:36)
#4      ModelGenerator.generateUnsafeDart (package:get_cli/common/utils/json_serialize/model_generator.dart:148:9)
#5      ModelGenerator.generateDartClasses (package:get_cli/common/utils/json_serialize/model_generator.dart:181:28)
#6      GenerateModelCommand.execute (package:get_cli/commands/impl/generate/model/model.dart:41:35)
<asynchronous suspension>
#7      main.<anonymous closure> (file:///Users/parthas/.pub-cache/hosted/pub.dev/get_cli-1.9.1/bin/get.dart:18:38)
<asynchronous suspension>
#8      main (file:///Users/parthas/.pub-cache/hosted/pub.dev/get_cli-1.9.1/bin/get.dart:18:9)
<asynchronous suspension>

**Comment by xyhuangjia** [comment]
> [@xyhuangjia](https://github.com/xyhuangjia) i tried but still getting issue Null check operator used on a null value #0 PubspecUtils.nullSafeSupport (package:get_cli/common/utils/pubspec/pubspec_utils.dart:146:76) [#1](https://github.com/jonataslaw/get_cli/pull/1) new TypeDefinition (package:get_cli/common/utils/json_serialize/sintaxe.dart:81:22) [#2](https://github.com/jonataslaw/get_cli/issues/2) new TypeDefinition.fromDynamic (package:get_cli/common/utils/json_serialize/sintaxe.dart:68:12) [#3](https://github.com/jonataslaw/get_cli/issues/3) ModelGenerator._generateClassDefinition (package:get_cli/common/utils/json_serialize/model_generator.dart:68:36) [#4](https://github.com/jonataslaw/get_cli/pull/4) ModelGenerator.generateUnsafeDart (package:get_cli/common/utils/json_serialize/model_generator.dart:148:9) [#5](https://github.com/jonataslaw/get_cli/pull/5) ModelGenerator.generateDartClasses (package:get_cli/common/utils/json_serialize/model_generator.dart:181:28) [#6](https://github.com/jonataslaw/get_cli/issues/6) GenerateModelCommand.execute (package:get_cli/commands/impl/generate/model/model.dart:41:35) [#7](https://github.com/jonataslaw/get_cli/pull/7) main. (file:///Users/parthas/.pub-cache/hosted/pub.dev/get_cli-1.9.1/bin/get.dart:18:38) [#8](https://github.com/jonataslaw/get_cli/pull/8) main (file:///Users/parthas/.pub-cache/hosted/pub.dev/get_cli-1.9.1/bin/get.dart:18:9)

try `dart flutter pub global activate get_cli`
