### ISSUE TITLE
Error on create page 

### ISSUE THREAD

**Issue by JaydeepSinroja** [jonataslaw/get_cli#245]
when i try to create page than error occured and after that says,  "The page [page_name] already exists" but actually there is no page on that name

Unhandled exception:
type 'String' is not a subtype of type 'Map<dynamic, dynamic>' in type cast
#0      PubspecUtils._extraFolder.<anonymous closure> (package:get_cli/common/utils/pubspec/pubspec_utils.dart:46:32)
#1      _PubValue.value (package:get_cli/common/utils/pubspec/pubspec_utils.dart:172:26)
#2      PubspecUtils.extraFolder (package:get_cli/common/utils/pubspec/pubspec_utils.dart:57:48)
#3      CreatePageCommand._writeFiles (package:get_cli/commands/impl/create/page/page.dart:80:36)
#4      CreatePageCommand.checkForAlreadyExists (package:get_cli/commands/impl/create/page/page.dart:74:7)
#5      CreatePageCommand.execute (package:get_cli/commands/impl/create/page/page.dart:38:5)
#6      main (file:///C:/Users/appit/AppData/Local/Pub/Cache/git/get_cli-0cbdef3d191a49f371315fb6ab899e32dfc64358/bin/get.dart:18:23)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

  1) Yes!
  2) No
  3) I want to rename
The page [page_name] already exists, do you want to overwrite it? [1]  
Unhandled exception:
type 'String' is not a subtype of type 'Map<dynamic, dynamic>' in type cast
#0      PubspecUtils._extraFolder.<anonymous closure> (package:get_cli/common/utils/pubspec/pubspec_utils.dart:46:32)
#1      _PubValue.value (package:get_cli/common/utils/pubspec/pubspec_utils.dart:172:26)
#2      PubspecUtils.extraFolder (package:get_cli/common/utils/pubspec/pubspec_utils.dart:57:48)
#3      CreatePageCommand._writeFiles (package:get_cli/commands/impl/create/page/page.dart:80:36)
#4      CreatePageCommand.checkForAlreadyExists (package:get_cli/commands/impl/create/page/page.dart:64:9)
#5      CreatePageCommand.execute (package:get_cli/commands/impl/create/page/page.dart:38:5)
#6      main (file:///C:/Users/appit/AppData/Local/Pub/Cache/git/get_cli-0cbdef3d191a49f371315fb6ab899e32dfc64358/bin/get.dart:18:23)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

**Comment by JaydeepSinroja** [comment]
when i remove 
get_cli:
    sub_folder:false
than it's work fine
