### ISSUE TITLE
Unhandled exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by faizahmaddae** [jonataslaw/get_cli#281]
# get generate model on home with assets/models/server.json

Unhandled exception:
Null check operator used on a null value
#0      PubspecUtils.nullSafeSupport (package:get_cli/common/utils/pubspec/pubspec_utils.dart:146:76)
#1      new TypeDefinition (package:get_cli/common/utils/json_serialize/sintaxe.dart:81:22)
#2      new TypeDefinition.fromDynamic (package:get_cli/common/utils/json_serialize/sintaxe.dart:68:12)
#3      ModelGenerator._generateClassDefinition (package:get_cli/common/utils/json_serialize/model_generator.dart:68:36)
#4      ModelGenerator.generateUnsafeDart (package:get_cli/common/utils/json_serialize/model_generator.dart:148:9)
#5      ModelGenerator.generateDartClasses (package:get_cli/common/utils/json_serialize/model_generator.dart:181:28)
#6      GenerateModelCommand.execute (package:get_cli/commands/impl/generate/model/model.dart:41:35)
<asynchronous suspension>
#7      main.<anonymous closure> (file:///Users/faiz/.pub-cache/hosted/pub.dev/get_cli-1.9.1/bin/get.dart:18:38)
<asynchronous suspension>
#8      main (file:///Users/faiz/.pub-cache/hosted/pub.dev/get_cli-1.9.1/bin/get.dart:18:9)
<asynchronous suspension>

**Comment by pimdo** [comment]
Had same issue, fixed by adding extra field `sdkConstraint` to pubspec.yaml:
```yaml
environment:
  sdk: ^3.5.3
  sdkConstraint: ">=2.12.0 <3.5.3"

**Comment by knottx** [comment]
See this #283

**Comment by whitecodel** [comment]
You can try this **CLI** tools for generating models

https://github.com/whitecodel/jsontodart
