### ISSUE TITLE
cannot create child page on module (windows) - NoSuchMethodError: The getter 'path' was called on null.

### ISSUE THREAD

**Issue by limsocheat** [jonataslaw/get_cli#64]
I want to create a child page on the parent page: 
`get create page:takeaway_checkout on takeaway`

But it created only empty folder with error message: 

```
✖  + Folder .\lib\app\modules\takeaway\takeaway_checkout not found

Unhandled exception:
NoSuchMethodError: The getter 'path' was called on null.
Receiver: null
Tried calling: path
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      Structure.model (package:get_cli/core/structure.dart:68:20)
#2      handleFileCreate (package:get_cli/functions/create/create_single_file.dart:20:31)
#3      CreatePageCommand._writeFiles (package:get_cli/commands/impl/create/page/page.dart:76:26)
#4      CreatePageCommand.checkForAlreadyExists (package:get_cli/commands/impl/create/page/page.dart:69:7)
#5      CreatePageCommand.execute (package:get_cli/commands/impl/create/page/page.dart:33:5)
#6      main (file:///C:/Users/AKbalthom/AppData/Local/Pub/Cache/git/get_cli-c27ea6d11ec0efcd1c9f72ab3726467268ec0855/bin/get.dart:18:
23)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

The page [takeaway_checkout] already exists, do you want to overwrite it?

  1) Yes!
  2) No
  3) I want to rename
```

Even I chose option 1(yes), it still creates an empty folder only.

**Comment by na2axl** [comment]
Hey, I've just installed get_cli today, but I have the same issue. Trying to run `get create page:chats on home`

```bash
✖  + Folder .\lib\app\modules\home\chats not found

Unhandled exception:
NoSuchMethodError: The getter 'path' was called on null.
Receiver: null
Tried calling: path
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      Structure.model (package:get_cli/core/structure.dart:68:20)
#2      handleFileCreate (package:get_cli/functions/create/create_single_file.dart:16:31)
#3      CreatePageCommand._writeFiles (package:get_cli/commands/impl/create/page/page.dart:67:26)
#4      CreatePageCommand.execute (package:get_cli/commands/impl/create/page/page.dart:51:13)
#5      main (file:///C:/Dev_Tools/flutter/.pub-cache/hosted/pub.dartlang.org/get_cli-1.4.5/bin/get.dart:15:23)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by syw0602** [comment]
Me too

**Comment by Cinux-Chosan** [comment]
same error!

**Comment by mma-amini** [comment]
Me too

**Comment by Charl0tter** [comment]
@CpdnCristiano

**Comment by CpdnCristiano** [comment]
what's your version?

**Comment by Charl0tter** [comment]
> 你的版本是什么？

![image](https://user-images.githubusercontent.com/23480626/121030329-f4936e00-c7db-11eb-8b88-214405bb4b3f.png)

**Comment by Charl0tter** [comment]
> 你的版本是什么？

![image](https://user-images.githubusercontent.com/23480626/121030661-43410800-c7dc-11eb-9607-9b4b1560c9b2.png)

**Comment by axu6705** [comment]
Not resolved yet

**Comment by CpdnCristiano** [comment]
Hello, sorry for the delay in resolution, I currently have no windows to test

**Comment by Shadiul** [comment]
please fix it, pleaseeeeeeeee 😢

**Comment by dragongesa** [comment]
same here :(

**Comment by dragongesa** [comment]
any update guys?

**Comment by ridwanwong** [comment]
any update?
Windows 10

**Comment by shahidpharm** [comment]
Same error to me. I am using windows 10

**Comment by syssam** [comment]
same here :(

**Comment by agusprayogi02** [comment]
me too :(
